[project]
name = "ising-mc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ELW", email = "erik.weerda@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "scipy>=1.18.1",
]

[project.scripts]
ising-mc = "ising_mc:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
